### ISSUE TITLE
Possible "watcher" leak

### ISSUE THREAD

**Issue by amoghe** [nex3/rb-inotify#32]
When a new ```Watcher``` is created, it adds itself to the notifiers hash (of watchers) using this:
```
@notifier.watchers[@id] = self
```

However, when the same watcher is now ```#close```d, it does not delete itself from the hash. 

This causes the watcher to never get GC'ed because the notifier hash will always contain a reference to it. Now a sequence of constantly changing watchers will result in several "leaked" objects.

Similarly when a ```Notifier``` is ```#close```d , it does not empty its Hash. It simply closes the underlying fd and returns.

Both of these fixes should be trivial (unless I'm missing something).

**Comment by njam** [comment]
I think this is merged and released, so this could be closed?

**Comment by amoghe** [comment]
@njam : done
