### ISSUE TITLE
Add License information to Gemspec

### ISSUE THREAD

**Issue by coreyhaines** [nex3/rb-inotify#34]
This will make it show up on rubygems.org. I'm doing due diligence on our gems and need to find out the licenses for all the gems. Having it show up on rubygems.org cuts out the step of having to go to the github repo.

**Comment by CalebFenton** [comment]
This can be closed as of https://github.com/nex3/rb-inotify/commit/6cecf6a645e75756f3d26ced8b8a700b4271b166
