### ISSUE TITLE
Ability to exclude certain files when using recursive watch

### ISSUE THREAD

**Issue by shrutika10** [nex3/rb-inotify#48]
We need to be able to exclude certain files when using recursive watch. Currently i did not find anything. Does it already exist? How do we use it?

**Comment by digitalextremist** [comment]
I personally use `find` and individually watch files that I do want.

**Comment by nex3** [comment]
Unless you're individually calling it file-by-file, inotify watches *directories*, not files. You'll just need to filter out the events after the fact.

**Comment by wmakley** [comment]
Just ran into this problem when using docker. I had a volume for postgresql data owned by root in my project, and rb-inotify just crashed. I'm moving it elsewhere as a workaround, but it would be nice to ignore it and not crash.

**Comment by alexanderadam** [comment]
Having the same issue right now. So is it somehow possible to ignore certain directories?
